name: ci 


on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: windows
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Add this line to fetch the full history      
      - name: TGmanual
        run: |
          git config user.name TGD-HW
          git config user.email puczok@tgdrives.cz
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 


      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material
      - run: pip install pymdown-extensions
      - run: pip install mkdocs-static-i18n
      - run: pip install mkdocs-glightbox
      - run: pip install mkdocs-git-committers-plugin-2
      - run: pip install mkdocs-git-revision-date-localized-plugin
      - run: mkdocs build
      - run: mkdocs gh-deploy --force